class_mapping = {
    "class_1": "Pink Primrose",
    "class_2": "Hard_leaved Pocket Orchid",
    "class_3": "Canterbury Bells",
    "class_4": "Sweet Pea",
    "class_5": "English Marigold",
    "class_6": "Tiger Lily",
    "class_7": "Moon Orchid",
    "class_8": "Bird of Paradise",
    "class_9": "Monkshood",
    "class_10": "Globe Thistle",
    "class_11": "Snapdragon",
    "class_12": "Colt's Foot",
    "class_13": "King Protea",
    "class_14": "Spear Thistle",
    "class_15": "Yellow Iris",
    "class_16": "Globe Flower",
    "class_17": "Purple Coneflower",
    "class_18": "Peruvian Lily",
    "class_19": "Balloon Flower",
    "class_20": "Giant White Arum Lily",
    "class_21": "Fire Lily",
    "class_22": "Pincushion Flower",
    "class_23": "Fritillary",
    "class_24": "Red Ginger",
    "class_25": "Grape Hyacinth",
    "class_26": "Corn Poppy",
    "class_27": "Prince of Wales Feathers",
    "class_28": "Stemless Gentian",
    "class_29": "Artichoke",
    "class_30": "Sweet William",
    "class_31": "Carnation",
    "class_32": "Garden Phlox",
    "class_33": "Love in the Mist",
    "class_34": "Mexican Aster",
    "class_35": "Alpine Sea Holly",
    "class_36": "Ruby_lipped Cattleya",
    "class_37": "Cape Flower",
    "class_38": "Great Masterwort",
    "class_39": "Siam Tulip",
    "class_40": "Lenten Rose",
    "class_41": "Barberton Daisy",
    "class_42": "Daffodil",
    "class_43": "Sword Lily",
    "class_44": "Poinsettia",
    "class_45": "Bolero Deep Blue",
    "class_46": "Wallflower",
    "class_47": "Marigold",
    "class_48": "Buttercup",
    "class_49": "Oxeye Daisy",
    "class_50": "Common Dandelion",
    "class_51": "Petunia",
    "class_52": "Wild Pansy",
    "class_53": "Primula",
    "class_54": "Sunflower",
    "class_55": "Pelargonium",
    "class_56": "Bishop of Llandaff",
    "class_57": "Gaura",
    "class_58": "Geranium",
    "class_59": "Orange Dahlia",
    "class_60": "Pink_Yellow Dahlia",
    "class_61": "Cautleya Spicata",
    "class_62": "Japanese Anemone",
    "class_63": "Black_eyed Susan",
    "class_64": "Silverbush",
    "class_65": "Californian Poppy",
    "class_66": "Osteospermum",
    "class_67": "Spring Crocus",
    "class_68": "Bearded Iris",
    "class_69": "Windflower",
    "class_70": "Tree Poppy",
    "class_71": "Gazania",
    "class_72": "Azalea",
    "class_73": "Water Lily",
    "class_74": "Rose",
    "class_75": "Thorn Apple",
    "class_76": "Morning Glory",
    "class_77": "Passion Flower",
    "class_78": "Lotus",
    "class_79": "Toad Lily",
    "class_80": "Anthurium",
    "class_81": "Frangipani",
    "class_82": "Clematis",
    "class_83": "Hibiscus",
    "class_84": "Columbine",
    "class_85": "Desert Rose",
    "class_86": "Tree Mallow",
    "class_87": "Magnolia",
    "class_88": "Cyclamen",
    "class_89": "Watercress",
    "class_90": "Canna Lily",
    "class_91": "Hippeastrum",
    "class_92": "Bee Balm",
    "class_93": "Ball Moss",
    "class_94": "Foxglove",
    "class_95": "Bougainvillea",
    "class_96": "Camellia",
    "class_97": "Mallow",
    "class_98": "Mexican Petunia",
    "class_99": "Bromelia",
    "class_100": "Blanket Flower",
    "class_101": "Trumpet Creeper",
    "class_102": "Blackberry Lily"
}
