name: Python Flask CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12.7]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install gdown
        if [ -f outlier-detection/requirements.txt ]; then pip install -r outlier-detection/requirements.txt; fi

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Download model file from Google Drive
      run: |
        echo "Downloading model from Google Drive..."
        gdown https://drive.google.com/uc?id=YOUR_FILE_ID -O outlier-detection/flower_model.pth

    - name: Run tests
      run: |
        cd outlier-detection
        python -m unittest discover -s tests
        cd ..

    - name: Check code coverage
      run: |
        pip install coverage
        cd outlier-detection
        coverage run -m unittest discover -s tests
        coverage report
        echo "Deleting model file after tests..."
        rm -f flower_model.pth

        coverage report
